-- TSDB超级表 iotsun--
create table iot_sun (
ts timestamp,
id binary(20),
address binary(20),
ambient_temperature float,
temperature1 float,
temperature2 float,
temperature3 float,
temperature4 float,
temperature5 float,
dew_point float,
ambient_humidity float,
land_humidity1 float,
land_humidity2 float,
land_humidity3 float,
flow_of_water float,
salinity float,
water_level float,
co float,
co2 float,
evaporation float,
pressure float,
wind_direction float,
wind_speed float,
average_wind_speed_2 float,
average_wind_speed_10 float,
cumulative_rainfall_interval float,
daily_cumulative_rainfall float,
cumulative_sunshine_interval float,
daily_cumulative_sunshine float,
total_radiation float,
divergent_radiation float,
direct_radiation float,
net_radiation float,
photosynthetic_radiation float,
ultraviolet_radiation float,
soil_heat_flux1 float,
total_radiation_interval_cumulative float,
cumulative_divergent_radiation_interval float,
cumulative_direct_radiation_interval float,
cumulative_net_radiation_interval float,
cumulative_interval_photosynthetic_radiation float,
cumulative_interval_ultraviolet_radiation float,
soil_heat_flux2 float,
daily_cumulative_total_radiation float,
daily_accumulation_of_scattered_radiation float,
direct_radiation_days_accumulation float,
daily_cumulative_net_radiation float,
daily_accumulation_of_photosynthetic_radiation float,
daily_accumulation_of_ultraviolet_radiatssion float,
soil_heat_flux3 float,
illumination float ,
electric_quantity float
 )
tags (equipment_type binary(20),identification_id binary(20) );
-- TSDB超级表 iotsun2--
create table iot_sun2 (
          ts timestamp,
          id binary(20),
          address binary(20),
          ambient_temperature  float,
          temperature1  float,
          temperature2  float,
          temperature3  float,
          temperature4  float,
          temperature5  float,
          dew_point  float,
          ambient_humidity  float,
          land_humidity1  float,
          land_humidity2 float,
          land_humidity3  float,
          co2 float,
          evaporation float,
          pressure float,
          total_radiation_1 float,
          divergent_radiation float,
          direct_radiation float,
          total_radiation_2 float,
          net_radiation float,
          photosynthetic_radiation float,
          ultraviolet_radiation float,
          soil_heat_flux1 float,
          wind_direction float,
          wind_speed float,
          average_wind_speed_2minute float,
          average_wind_speed_10minute float,
          cumulative_rainfall_interval float,
          cumulative_sunshine_interval float,
          total_radiation1_interval_cumulative float,
          cumulative_divergent_radiation_interval float,
          cumulative_direct_radiation_interval float,
          total_radiation2_interval_cumulative float,
          cumulative_net_radiation_interval float,
          cumulative_interval_of_photosynthetic_radiation float,
          cumulative_interval_of_ultraviolet_radiation float,
          soil_heat_flux2 float,
          daily_cumulative_rainfall float,
          daily_cumulative_sunshine float,
          daily_cumulative_total_radiation1 float,
          daily_accumulation_of_scattered_radiation float,
          daily_accumulation_of_direct_radiation float,
          daily_cumulative_total_radiation2 float,
          daily_cumulative_of_net_radiation float,
          daily_cumulative_photosynthetic_radiation float,
          daily_cumulative_ultraviolet_radiation float,
          soil_heat_flux3 float,
          illumination float,
          electric_quantity float,
          pm2_5 float
)
tags (equipment_type binary(20),identification_id binary(20) );
-- 5016设备表--
create table t_iot_sun5016 using iot_sun tags ('sun','40326904964');
-- 5015设备表--
create table t_iot_sun5015 using iot_sun2 tags ('sun2','40378510054');
//        //5016
//        byte[] bytes1 = new byte[]{(byte) 0x7B, (byte) 0x81, (byte) 0x00 ,(byte) 0x10,
//                (byte) 0x34, (byte) 0x30, (byte) 0x33, (byte) 0x32, (byte) 0x36, (byte) 0x39, (byte) 0x30, (byte) 0x34, (byte) 0x39, (byte) 0x36, (byte) 0x34,
//                (byte) 0x7B};

//        5015
        byte[] bytes1 = new byte[]{(byte) 0x7B, (byte) 0x81, (byte) 0x00 ,(byte) 0x10,
                (byte) 0x34, (byte) 0x30, (byte) 0x33, (byte) 0x37, (byte) 0x38, (byte) 0x35, (byte) 0x31, (byte) 0x30, (byte) 0x30, (byte) 0x35, (byte) 0x34,
                (byte) 0x7B};
--诱娥超级表 --
create table iot_decoy (
ts timestamp,
id binary(20),
electric_quantity binary(20),
temperature float ,
humidity float ,
sim binary(20),
state_electrical_machine binary(20),
weight float ,
ip binary(20),
state binary(20),
latitude float ,
latitude_hemisphere  binary(20),
longitude float ,
longitude_hemisphere binary(20),
surface_velocity float ,
ground_heading float ,
magnetic_declination float ,
direction_magnetic_declination binary(20),
mode_indication binary(20)
) tags (device_id binary(20));